### ISSUE TITLE
How to add "FOR UPDATE" for SELECT?

### ISSUE THREAD

**Issue by gzlboy** [Masterminds/squirrel#385]
for example:
```
SELECT * FROM tableA WHERE id = 1 FOR UPDATE
```

**Comment by jonasc** [comment]
Since I also just stumbled upon this and to prevent [this scenario](https://xkcd.com/979/):

![wisdom_of_the_ancients](https://github.com/user-attachments/assets/ddb00ec0-2f78-45f7-bce0-153dfe43e443)

It seems that the only way to do is, is to use the [`Suffix`](https://github.com/Masterminds/squirrel/blob/1ded5784535dcffa4e175d4efbd1ca2706927758/select.go#L396) method. E.g. 
 ```go
squirrel.Select("*").
    From("tableA").
    Where(squirrel.Eq{"id": 1}).
    Suffix("FOR UPDATE")
```
