### ISSUE TITLE
Support for WITH queries

### ISSUE THREAD

**Issue by itsjamie** [Masterminds/squirrel#65]
Hey there, I was looking for a way to write a WITH query for a Update, and then select the resulting rows along with some of the relational data, it will also be nice to able to chain these WITH statements together.

I'm not sure if this is supported in the current query builder, if it is, did I miss the documentation? The reason we like squirrel is it lets us conditionally build the insert / update statements, and composing the selects makes the code for filtering/sorting much cleaner.

Below is a simple example for what I'm looking for and hopefully I've overlooked it somewhere, thanks!

``` sql
WITH inserted_job AS (
   INSERT INTO jobs SET status = 1, progress = 54 WHERE ... RETURNING ...
)
SELECT status from inserted_job join .... 
```

**Comment by lann** [comment]
For some simple use cases you might get away with using .Prefix and/or .Suffix to do this, but for more complex queries I would recommend calling the ```ToSql() (sqlStr string, args []interface{}, err error)``` methods that all squirrel builders support and constructing your query from those.

For your example, you could do something like this (untested / needs error checking):
```go
insertSql, insertArgs, _ := insertBuilder.ToSql()
selectSql, selectArgs, _ := selectBuilder.ToSql()
withSql := fmt.Sprintf("WITH inserted_job AS (%s) %s", insertSql, selectSql)
withArgs := append(insertArgs, selectArgs)
db.Query(withSql, withArgs)
```

That said, since WITH is a standard construct I would be happy to accept a PR...

**Comment by itsjamie** [comment]
This would work for MySQL dialects however where we are using Postgres and it has the ordinal placeholder we end up repeating the arguments starting `$1`.

**Comment by jbaum98** [comment]
To deal with that, you can wait until the very end to convert to Postgresql dollar placeholders using `sq.Dollar.ReplacePlaceholders`.
