### ISSUE TITLE
Using subquery in WHERE ... IN ...

### ISSUE THREAD

**Issue by sungwoncho** [Masterminds/squirrel#70]
Using the latest version of squirrel, when I do the following:

``` go
builder := psql.Select("j.title").
    From("jobs j").
    Join("companies c on j.company_id = c.id").
    Where("c.id IN ($1)", "SELECT * FROM ...")
```

I get

```
pq: invalid input syntax for integer: "SELECT * FROM ..."
```

Therefore I have to use `fmt.Sprintf`:

``` go
builder := psql.Select("j.title").
    From("jobs j").
    Join("companies c on j.company_id = c.id").
    Where(fmt.Sprintf("c.id IN (%s)", "SELECT * FROM ...")
```

**Comment by elewis787** [comment]
place holders don't allow any sql statements to be added. I would say this is desired.

**Comment by msaron** [comment]
@sungwoncho I would change the query to use EXISTS instead of IN. I always use EXISTS because it uses the index for lookups and the query is much easier to construct. Using an IN query does not make use of an index as you are passing a list of values. You can easily change your code to:


    Where("exists(select 1 from table2 where table2.table1_id = c.id)")

This will execute much faster.
