### ISSUE TITLE
Support *Context methods from database/sql in Go 1.8

### ISSUE THREAD

**Issue by cv** [Masterminds/squirrel#88]
New API in Go 1.8 allows passing a `context.Context` to `Exec`, `Query` and `QueryRow` (via the `ExecContext`, `QueryContext` and `QueryRowContext` methods, respectively.)

Drivers can take advantage of this in numerous ways - we would particularly enjoy distributed tracing in Lightstep.

**Comment by dim** [comment]
:+1:

**Comment by lann** [comment]
Fixed by #98.

**Comment by tiziano88** [comment]
Is there any point in keeping the non-Context methods around? I guess only for backwards compatibility with Go pre-1.8, but it would be nice to clean this up at some point and assume that everyone has moved on to the newer version?

**Comment by lann** [comment]
Squirrel will not intentionally break backwards compatibility in its exported interface.

**Comment by tiziano88** [comment]
Forever? Or is the plan to support latest Go and `N` older versions?

**Comment by lann** [comment]
This isn't about what versions of Go are supported, its about the exported interface. If I needed to break the exported interface for some reason I would bump the branch to v2.

**Comment by tiziano88** [comment]
Got it, thanks! I think that removing methods from an interface, though formally a breaking change, in practice is unlikely to do harm, since if a struct defines the extra methods they will just be ignored. Of course if someone was using the interface for their own purposes and calling these methods directly on it, then it would break them, but I feel that is unlikely to be the case in practice. Anyway, I may fork it for my own use case for now, and will keep an eye on this. Thanks for all the hard work!
